CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE zones
    ADD COLUMN IF NOT EXISTS elevation_m DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS height_m DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS is_tunnel BOOLEAN,
    ADD COLUMN IF NOT EXISTS is_bridge BOOLEAN,
    ADD COLUMN IF NOT EXISTS geom_3d geometry(GeometryZ, 4326);

ALTER TABLE camera_events
    ADD COLUMN IF NOT EXISTS elevation_m DOUBLE PRECISION;

ALTER TABLE sig_events
    ADD COLUMN IF NOT EXISTS elevation_m DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS track_level VARCHAR(16);

CREATE INDEX IF NOT EXISTS idx_zones_geom_3d
    ON zones
    USING GIST (geom_3d);
