import { useEffect, useMemo, useState } from 'react'
import { listAlerts, getAlertStats } from '../api/alerts'
import type { AlertSeverity, AlertStats } from '../types/api'
import { AlertRow } from '../components/AlertRow'
import { useLiveAlertsContext } from '../context/LiveAlertsContext'

const SEVS: AlertSeverity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']

export function DashboardPage() {
  const [stats, setStats] = useState<AlertStats | null>(null)
  const [loading, setLoading] = useState(true)
  const { alerts, seedAlerts } = useLiveAlertsContext()

  useEffect(() => {
    let active = true
    Promise.all([listAlerts({ limit: 50 }), getAlertStats()])
      .then(([list, s]) => {
        if (!active) return
        seedAlerts(list)
        setStats(s)
      })
      .catch((e) => {
        console.error('Dashboard load failed', e)
        if (active) setStats(null)
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [seedAlerts])

  const liveStats = useMemo<AlertStats | null>(() => {
    if (!stats) return null
    const bySeverity: AlertStats['bySeverity'] = {
      CRITICAL: 0,
      HIGH: 0,
      MEDIUM: 0,
      LOW: 0,
    }
    for (const a of alerts) {
      if (a.severity in bySeverity) {
        bySeverity[a.severity] += 1
      }
    }
    return {
      total: alerts.length,
      bySeverity,
    }
  }, [alerts, stats])

  return (
    <>
      <div className="page-header">
        <div>
          <h2>Operator dashboard</h2>
          <p>Real-time feed of alerts generated by the correlation engine.</p>
        </div>
      </div>

      <div className="stat-grid">
        <div className="card">
          <h3>Total alerts</h3>
          <div className="value">{liveStats?.total ?? stats?.total ?? '—'}</div>
        </div>
        {SEVS.map((s) => (
          <div key={s} className={`card sev-${s}`}>
            <h3>{s}</h3>
            <div className="value">{liveStats?.bySeverity?.[s] ?? stats?.bySeverity?.[s] ?? 0}</div>
          </div>
        ))}
      </div>

      <h3>Latest alerts</h3>
      {loading && <p className="muted">Loading…</p>}
      {!loading && alerts.length === 0 && (
        <p className="muted">
          No alerts yet. Head to the <b>Operations</b> console to receive some events.
        </p>
      )}
      <div className="alert-list">
        {alerts.slice(0, 30).map((a) => (
          <AlertRow key={a.id} alert={a} />
        ))}
      </div>
    </>
  )
}
