import { useEffect, useMemo, useState } from 'react'
import { listAlerts, getAlertStats } from '../api/alerts'
import type { AlertStats } from '../types/api'
import { AlertRow } from '../components/AlertRow'
import { useLiveAlertsContext } from '../context/LiveAlertsContext'

const STAT_CARDS = [
  {
    key: 'total'    as const,
    label: 'Total Alerts',
    icon: '🔔',
    iconBg: 'rgba(37,99,235,0.25)',
    iconColor: '#3b82f6',
    accent: '#3b82f6',
  },
  {
    key: 'CRITICAL' as const,
    label: 'Critical',
    icon: '🔴',
    iconBg: 'rgba(185,28,28,0.25)',
    iconColor: '#dc2626',
    accent: '#dc2626',
  },
  {
    key: 'HIGH'     as const,
    label: 'High',
    icon: '🔥',
    iconBg: 'rgba(239,68,68,0.2)',
    iconColor: '#ef4444',
    accent: '#ef4444',
  },
  {
    key: 'MEDIUM'   as const,
    label: 'Medium',
    icon: '⚠️',
    iconBg: 'rgba(245,158,11,0.2)',
    iconColor: '#f59e0b',
    accent: '#f59e0b',
  },
  {
    key: 'LOW'      as const,
    label: 'Low',
    icon: 'ℹ️',
    iconBg: 'rgba(99,102,241,0.2)',
    iconColor: '#6366f1',
    accent: '#6366f1',
  },
]

export function DashboardPage() {
  const [stats, setStats] = useState<AlertStats | null>(null)
  const [loading, setLoading] = useState(true)
  const { alerts, seedAlerts } = useLiveAlertsContext()

  useEffect(() => {
    let active = true
    Promise.all([listAlerts({ limit: 50 }), getAlertStats()])
      .then(([list, s]) => {
        if (!active) return
        seedAlerts(list)
        setStats(s)
      })
      .catch((e) => {
        console.error('Dashboard load failed', e)
        if (active) setStats(null)
      })
      .finally(() => { if (active) setLoading(false) })
    return () => { active = false }
  }, [seedAlerts])

  const liveStats = useMemo<AlertStats | null>(() => {
    if (!stats) return null
    const bySeverity: AlertStats['bySeverity'] = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 }
    for (const a of alerts) {
      if (a.severity in bySeverity) bySeverity[a.severity] += 1
    }
    return { total: alerts.length, bySeverity }
  }, [alerts, stats])

  function getValue(key: typeof STAT_CARDS[number]['key']) {
    if (key === 'total') return liveStats?.total ?? stats?.total ?? 0
    return liveStats?.bySeverity?.[key] ?? stats?.bySeverity?.[key] ?? 0
  }

  return (
    <>
      <div className="page-header">
        <div>
          <h2>Operator Dashboard</h2>
          <p>Real-time feed of alerts generated by the correlation engine.</p>
        </div>
      </div>

      <div className="dash-stat-row">
        {STAT_CARDS.map((c) => (
          <div
            key={c.key}
            className="dash-stat-card"
            style={{ '--card-accent': c.accent } as React.CSSProperties}
          >
            <div className="dash-stat-top" />
            <div className="dash-stat-body">
              <div className="dash-stat-icon" style={{ background: c.iconBg }}>
                <span>{c.icon}</span>
              </div>
              <div className="dash-stat-info">
                <span className="dash-stat-value">{getValue(c.key)}</span>
                <span className="dash-stat-label">{c.label}</span>
              </div>
            </div>
          </div>
        ))}
      </div>

      <h3>Latest alerts</h3>

      {loading && <p className="muted">Loading…</p>}
      {!loading && alerts.length === 0 && (
        <p className="muted">
          No alerts yet. Head to the <b>Operations</b> console to receive some events.
        </p>
      )}
      <div className="alert-list">
        {alerts.slice(0, 30).map((a) => (
          <AlertRow key={a.id} alert={a} />
        ))}
      </div>
    </>
  )
}
