import { useEffect, useState } from 'react'
import { listAlerts } from '../api/alerts'
import type { Alert, AlertSeverity } from '../types/api'

const SEVS: ('' | AlertSeverity)[] = ['', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']

export function HistoryPage() {
  const [severity, setSeverity] = useState<'' | AlertSeverity>('')
  const [alerts, setAlerts] = useState<Alert[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true)
    listAlerts({ severity: severity || undefined, limit: 500 })
      .then(setAlerts)
      .finally(() => setLoading(false))
  }, [severity])

  return (
    <>
      <div className="page-header">
        <div>
          <h2>Alert history</h2>
          <p>Chronological timeline of all alerts generated by the system.</p>
        </div>
      </div>

      <div className="card" style={{ marginBottom: 20 }}>
        <div className="form-row">
          <label>Severity</label>
          <select value={severity} onChange={(e) => setSeverity(e.target.value as AlertSeverity | '')}>
            {SEVS.map((s) => (
              <option key={s} value={s}>
                {s || 'All'}
              </option>
            ))}
          </select>
        </div>
      </div>

      {loading && <p className="muted">Loading…</p>}
      {!loading && alerts.length === 0 && <p className="muted">No alerts match.</p>}

      <div className="timeline">
        {alerts.map((a) => (
          <div key={a.id} className={`timeline-item sev-${a.severity}`}>
            <div className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <b>
                  [{a.severity}] {a.type.replace('_', ' ')}
                </b>
                <time className="muted">
                  {new Date(a.createdAt).toLocaleString()}
                </time>
              </div>
              <div style={{ marginTop: 6 }}>{a.message}</div>
              {a.zoneName && (
                <div className="muted" style={{ marginTop: 4 }}>
                  Zone: {a.zoneName}
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </>
  )
}
