/**
 * Interface language: English or French.
 *
 * Keys are stable identifiers rather than English sentences, so rewording
 * the English copy never silently orphans a French translation — the pair
 * stays linked by the key. `en` is written out in full for the same reason:
 * both languages sit side by side in one file, which is what makes a
 * missing or stale translation visible instead of invisible.
 *
 * Scope note: alert *messages* ("Car on track 'X' — emergency stop
 * required") are composed by the backend's correlation rules and stored on
 * the alert, so they arrive already written and are not translated here.
 * Everything the interface itself says — navigation, headings, labels,
 * buttons, severities, statuses, alert type names — is.
 */

import type { Language } from './prefs'
import { loadPrefs, savePrefs } from './prefs'

export type { Language }

type Dict = Record<string, string>

const en: Dict = {
  /* ── brand & navigation ── */
  'brand.subtitle': 'ONCF Security Platform',
  'nav.section': 'Navigation',
  'nav.dashboard': 'Dashboard',
  'nav.live': 'Live Watch',
  'nav.map3d': '3D Map',
  'nav.history': 'History',
  'nav.analytics': 'Analytics',
  'nav.settings': 'Settings',
  'nav.users': 'Users',
  'nav.cameras': 'Cameras',
  'nav.zones': 'Zones',
  'nav.camerasLive': 'AI cameras: {live}/{total} live',
  'nav.feed': 'Live feed: {state}',
  'nav.feed.connected': 'connected',
  'nav.feed.connecting': 'connecting',
  'nav.feed.closed': 'disconnected',
  'nav.signOut': 'Sign out',

  /* ── roles ── */
  'role.VIEWER': 'Viewer',
  'role.OPERATOR': 'Operator',
  'role.ADMIN': 'Admin',

  /* ── severities ── */
  'severity.LOW': 'Low',
  'severity.MEDIUM': 'Medium',
  'severity.HIGH': 'High',
  'severity.CRITICAL': 'Critical',

  /* ── alert statuses ── */
  'status.NEW': 'New',
  'status.ACKNOWLEDGED': 'Acknowledged',
  'status.RESOLVED': 'Resolved',

  /* ── zone types ── */
  'zoneType.STATION': 'Station',
  'zoneType.TRACK': 'Track',
  'zoneType.RESTRICTED': 'Restricted',
  'zoneType.NORMAL': 'Normal',

  /* ── alert types ── */
  'alertType.INTRUSION': 'Intrusion',
  'alertType.OBJECT_ON_TRACK': 'Object on track',
  'alertType.TRACK_PROXIMITY': 'Track proximity',
  'alertType.LOITERING': 'Loitering',
  'alertType.FALL_DETECTED': 'Fall detected',
  'alertType.UNATTENDED_BAGGAGE': 'Unattended baggage',
  'alertType.CROWD_DENSITY': 'Crowd density',
  'alertType.ESCALATION': 'Escalation',
  'alertType.NIGHT_ACTIVITY': 'Night activity',
  'alertType.ANOMALY': 'Anomaly',
  'alertType.FUSION': 'Camera/SIG fusion',
  'alertType.STATION_ACTIVITY': 'Station activity',

  /* ── shared actions & states ── */
  'common.loading': 'Loading…',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.deleting': 'Deleting…',
  'common.close': 'Close',
  'common.all': 'All',
  'common.none': '—',
  'common.severity': 'Severity',
  'common.status': 'Status',
  'common.zone': 'Zone',
  'common.actions': 'Actions',
  'common.name': 'Name',
  'common.type': 'Type',
  'common.saved': 'Saved ✓',

  /* ── dashboard ── */
  'dashboard.title': 'Operator Dashboard',
  'dashboard.subtitle': 'Real-time feed of alerts generated by the correlation engine.',
  'dashboard.totalAlerts': 'Total Alerts',
  'dashboard.latest': 'Latest alerts',
  'dashboard.empty': 'No alerts yet. Alerts will appear here as cameras detect events.',
  'dashboard.allResolved': "No open alerts — everything's been resolved. Check History for past alerts.",
  'dashboard.acknowledge': 'Acknowledge',
  'dashboard.resolve': 'Resolve',
  'dashboard.map': 'Map',
  'alert.zone': 'Zone:',
  'alert.by': 'operator',
  'alert.acknowledgedBy': 'Acknowledged by',
  'alert.resolvedBy': 'Resolved by',
  'alert.notePlaceholder': 'Resolution note (optional)',
  'alert.confirmResolve': 'Confirm resolve',
  'alert.mapTitle': 'Fly to where this alert happened on the 3D map',

  /* ── history ── */
  'history.title': 'Alert history',
  'history.subtitle': 'Chronological timeline of all alerts generated by the system.',
  'history.empty': 'No alerts match.',
  'history.viewOnMap': '🗺 View on 3D map',
  'history.clearResolved': 'Clear resolved',
  'history.deleteAll': 'Delete all',
  'history.acknowledgedBy': 'Acknowledged by {who} · {when}',
  'history.resolvedBy': 'Resolved by {who} · {when}',
  'history.confirmDelete':
    'Delete this alert permanently?\n\n{label}\n\nThis cannot be undone.',
  'history.confirmClearResolved': 'Delete all {count} resolved alert(s)?',
  'history.confirmClearAll': 'Delete the ENTIRE alert history?',
  'history.keepsOpen': 'Open alerts (New / Acknowledged) are kept.',
  'history.wipesAll':
    'Every alert is removed, including ones still open. This cannot be undone.',
  'history.deleteFailed': 'Could not delete that alert',
  'history.clearFailed': 'Could not clear the alert history',
  'history.deleteTitle': 'Permanently remove this alert from the log',
  'history.clearResolvedTitle': 'Remove closed incidents, keep anything still open',
  'history.deleteAllTitle': 'Remove every alert, including open ones',

  /* ── settings ── */
  'settings.title': 'Settings',
  'settings.subtitle': 'Manage your alerts, location access, and appearance.',
  'settings.reset': 'Reset to defaults',
  'settings.group.alerts': 'Alerts',
  'settings.group.location': 'Location',
  'settings.group.appearance': 'Appearance',
  'settings.group.language': 'Language',
  'settings.notifications': 'Notifications',
  'settings.notifications.desc': 'Browser popup and sound on new alerts',
  'settings.notifications.allowed': 'Browser notifications allowed.',
  'settings.notifications.willAsk': 'The browser will ask for permission.',
  'settings.notifications.blocked':
    'Popups blocked by the browser — sounds still play. Allow notifications in the site permissions (padlock in the address bar) to restore them.',
  'settings.highCritical': 'High & Critical only',
  'settings.highCritical.desc': 'Suppress LOW and MEDIUM alerts',
  'settings.location': 'Location tracking',
  'settings.location.desc': 'Allow this station to use your browser geolocation',
  'settings.location.waiting': 'Waiting for the browser permission…',
  'settings.location.tracking': 'Tracking · {lat}, {lon}',
  'settings.location.accuracy': ' (±{m} m)',
  'settings.darkMode': 'Dark mode',
  'settings.darkMode.desc': 'Switch to a dark colour scheme',
  'settings.language': 'Interface language',
  'settings.language.desc': 'Language used across the whole application',

  /* ── login ── */
  'login.title': 'Hypervisor',
  'login.subtitle': 'ONCF Security Platform',
  'login.username': 'Username',
  'login.password': 'Password',
  'login.submit': 'Sign in',
  'login.submitting': 'Signing in…',

  /* ── analytics ── */
  'analytics.title': 'Analytics',
  'analytics.subtitle': 'Alert statistics and trends by severity, type and zone.',

  /* ── live watch ── */
  'live.title': 'Live Watch',
  'live.subtitle':
    'Every enabled AI camera runs in the background as long as this app is open in your browser — no Start click required. The hypervisor receives detections, runs correlation, and emits alerts for all of them in parallel.',

  /* ── 3D map ── */
  'map.title': '3D Map',
  'map.subtitle': 'Alerts placed on the terrain where they happened.',

  /* ── admin ── */
  'admin.users.title': 'Users',
  'admin.users.subtitle': 'Create, edit, and remove user accounts. Admin-only.',
  'admin.cameras.title': 'Cameras',
  'admin.cameras.subtitle': 'Register camera installations and their locations. Admin-only.',
  'admin.zones.title': 'Zones',
  'admin.zones.subtitle': 'Define surveillance zones — where and how alerts are graded. Admin-only.',
}

const fr: Dict = {
  /* ── marque & navigation ── */
  'brand.subtitle': 'Plateforme de sûreté ONCF',
  'nav.section': 'Navigation',
  'nav.dashboard': 'Tableau de bord',
  'nav.live': 'Surveillance directe',
  'nav.map3d': 'Carte 3D',
  'nav.history': 'Historique',
  'nav.analytics': 'Statistiques',
  'nav.settings': 'Paramètres',
  'nav.users': 'Utilisateurs',
  'nav.cameras': 'Caméras',
  'nav.zones': 'Zones',
  'nav.camerasLive': 'Caméras IA : {live}/{total} actives',
  'nav.feed': 'Flux temps réel : {state}',
  'nav.feed.connected': 'connecté',
  'nav.feed.connecting': 'connexion…',
  'nav.feed.closed': 'déconnecté',
  'nav.signOut': 'Déconnexion',

  /* ── rôles ── */
  'role.VIEWER': 'Observateur',
  'role.OPERATOR': 'Opérateur',
  'role.ADMIN': 'Administrateur',

  /* ── gravités ── */
  'severity.LOW': 'Faible',
  'severity.MEDIUM': 'Moyenne',
  'severity.HIGH': 'Élevée',
  'severity.CRITICAL': 'Critique',

  /* ── statuts d'alerte ── */
  'status.NEW': 'Nouvelle',
  'status.ACKNOWLEDGED': 'Acquittée',
  'status.RESOLVED': 'Résolue',

  /* ── types de zone ── */
  'zoneType.STATION': 'Gare',
  'zoneType.TRACK': 'Voie',
  'zoneType.RESTRICTED': 'Zone interdite',
  'zoneType.NORMAL': 'Normale',

  /* ── types d'alerte ── */
  'alertType.INTRUSION': 'Intrusion',
  'alertType.OBJECT_ON_TRACK': 'Objet sur la voie',
  'alertType.TRACK_PROXIMITY': 'Proximité de la voie',
  'alertType.LOITERING': 'Comportement suspect',
  'alertType.FALL_DETECTED': 'Chute détectée',
  'alertType.UNATTENDED_BAGGAGE': 'Bagage abandonné',
  'alertType.CROWD_DENSITY': 'Affluence',
  'alertType.ESCALATION': 'Escalade',
  'alertType.NIGHT_ACTIVITY': 'Activité nocturne',
  'alertType.ANOMALY': 'Anomalie',
  'alertType.FUSION': 'Fusion caméra/SIG',
  'alertType.STATION_ACTIVITY': 'Activité en gare',

  /* ── actions & états communs ── */
  'common.loading': 'Chargement…',
  'common.save': 'Enregistrer',
  'common.cancel': 'Annuler',
  'common.edit': 'Modifier',
  'common.delete': 'Supprimer',
  'common.deleting': 'Suppression…',
  'common.close': 'Fermer',
  'common.all': 'Toutes',
  'common.none': '—',
  'common.severity': 'Gravité',
  'common.status': 'Statut',
  'common.zone': 'Zone',
  'common.actions': 'Actions',
  'common.name': 'Nom',
  'common.type': 'Type',
  'common.saved': 'Enregistré ✓',

  /* ── tableau de bord ── */
  'dashboard.title': 'Poste opérateur',
  'dashboard.subtitle': "Flux temps réel des alertes générées par le moteur de corrélation.",
  'dashboard.totalAlerts': 'Alertes totales',
  'dashboard.latest': 'Dernières alertes',
  'dashboard.empty': "Aucune alerte pour l'instant. Les alertes apparaîtront ici dès qu'une caméra détecte un événement.",
  'dashboard.allResolved': "Aucune alerte ouverte — tout a été résolu. Consultez l'Historique pour les alertes passées.",
  'dashboard.acknowledge': 'Acquitter',
  'dashboard.resolve': 'Résoudre',
  'dashboard.map': 'Carte',
  'alert.zone': 'Zone :',
  'alert.by': 'opérateur',
  'alert.acknowledgedBy': 'Acquittée par',
  'alert.resolvedBy': 'Résolue par',
  'alert.notePlaceholder': 'Note de résolution (facultative)',
  'alert.confirmResolve': 'Confirmer la résolution',
  'alert.mapTitle': "Aller à l'endroit où cette alerte s'est produite sur la carte 3D",

  /* ── historique ── */
  'history.title': 'Historique des alertes',
  'history.subtitle': "Chronologie de toutes les alertes générées par le système.",
  'history.empty': 'Aucune alerte ne correspond.',
  'history.viewOnMap': '🗺 Voir sur la carte 3D',
  'history.clearResolved': 'Vider les résolues',
  'history.deleteAll': 'Tout supprimer',
  'history.acknowledgedBy': 'Acquittée par {who} · {when}',
  'history.resolvedBy': 'Résolue par {who} · {when}',
  'history.confirmDelete':
    'Supprimer définitivement cette alerte ?\n\n{label}\n\nCette action est irréversible.',
  'history.confirmClearResolved': 'Supprimer les {count} alerte(s) résolue(s) ?',
  'history.confirmClearAll': "Supprimer TOUT l'historique des alertes ?",
  'history.keepsOpen': 'Les alertes ouvertes (Nouvelle / Acquittée) sont conservées.',
  'history.wipesAll':
    'Toutes les alertes sont supprimées, y compris celles encore ouvertes. Cette action est irréversible.',
  'history.deleteFailed': "Impossible de supprimer cette alerte",
  'history.clearFailed': "Impossible de vider l'historique des alertes",
  'history.deleteTitle': "Retirer définitivement cette alerte du journal",
  'history.clearResolvedTitle':
    'Retirer les incidents clos, conserver ceux encore ouverts',
  'history.deleteAllTitle': 'Retirer toutes les alertes, y compris les ouvertes',

  /* ── paramètres ── */
  'settings.title': 'Paramètres',
  'settings.subtitle': "Gérez vos alertes, l'accès à la localisation et l'apparence.",
  'settings.reset': 'Réinitialiser',
  'settings.group.alerts': 'Alertes',
  'settings.group.location': 'Localisation',
  'settings.group.appearance': 'Apparence',
  'settings.group.language': 'Langue',
  'settings.notifications': 'Notifications',
  'settings.notifications.desc': "Fenêtre du navigateur et son à chaque nouvelle alerte",
  'settings.notifications.allowed': 'Notifications du navigateur autorisées.',
  'settings.notifications.willAsk': "Le navigateur va demander l'autorisation.",
  'settings.notifications.blocked':
    "Fenêtres bloquées par le navigateur — le son fonctionne toujours. Autorisez les notifications dans les permissions du site (cadenas dans la barre d'adresse) pour les rétablir.",
  'settings.highCritical': 'Élevée et Critique uniquement',
  'settings.highCritical.desc': 'Masquer les alertes FAIBLE et MOYENNE',
  'settings.location': 'Suivi de position',
  'settings.location.desc': 'Autoriser ce poste à utiliser la géolocalisation du navigateur',
  'settings.location.waiting': "En attente de l'autorisation du navigateur…",
  'settings.location.tracking': 'Suivi · {lat}, {lon}',
  'settings.location.accuracy': ' (±{m} m)',
  'settings.darkMode': 'Mode sombre',
  'settings.darkMode.desc': 'Basculer vers un thème sombre',
  'settings.language': "Langue de l'interface",
  'settings.language.desc': "Langue utilisée dans toute l'application",

  /* ── connexion ── */
  'login.title': 'Hypervisor',
  'login.subtitle': 'Plateforme de sûreté ONCF',
  'login.username': "Nom d'utilisateur",
  'login.password': 'Mot de passe',
  'login.submit': 'Se connecter',
  'login.submitting': 'Connexion…',

  /* ── statistiques ── */
  'analytics.title': 'Statistiques',
  'analytics.subtitle': 'Statistiques et tendances des alertes par gravité, type et zone.',

  /* ── surveillance directe ── */
  'live.title': 'Surveillance directe',
  'live.subtitle':
    "Chaque caméra IA activée fonctionne en arrière-plan tant que cette application est ouverte dans votre navigateur — aucun clic sur Démarrer n'est nécessaire. L'hyperviseur reçoit les détections, exécute la corrélation et émet les alertes pour toutes en parallèle.",

  /* ── carte 3D ── */
  'map.title': 'Carte 3D',
  'map.subtitle': 'Alertes positionnées sur le terrain où elles se sont produites.',

  /* ── administration ── */
  'admin.users.title': 'Utilisateurs',
  'admin.users.subtitle': "Créer, modifier et supprimer des comptes. Réservé aux administrateurs.",
  'admin.cameras.title': 'Caméras',
  'admin.cameras.subtitle': 'Enregistrer les installations de caméras et leurs positions. Réservé aux administrateurs.',
  'admin.zones.title': 'Zones',
  'admin.zones.subtitle': "Définir les zones de surveillance — où et comment les alertes sont graduées. Réservé aux administrateurs.",
}

const DICTS: Record<Language, Dict> = { en, fr }

let current: Language = 'en'
const listeners = new Set<() => void>()

/**
 * Looks up a key in the active language.
 *
 * Falls back to English, then to the key itself — a missing translation
 * should degrade to readable English, never to a blank space in the middle
 * of the interface.
 *
 * @param vars values for `{placeholder}` slots in the string
 */
/** Signature of {@link t}, for helpers that take the translator as a parameter. */
export type Translate = (key: string, vars?: Record<string, string | number>) => string

export function t(key: string, vars?: Record<string, string | number>): string {
  const raw = DICTS[current][key] ?? en[key] ?? key
  if (!vars) return raw
  return raw.replace(/\{(\w+)\}/g, (match, name: string) =>
    name in vars ? String(vars[name]) : match,
  )
}

export function getLanguage(): Language {
  return current
}

export function setLanguage(next: Language) {
  if (next === current) return
  current = next
  document.documentElement.lang = next
  const prefs = loadPrefs()
  savePrefs({ ...prefs, language: next })
  for (const listener of listeners) listener()
}

/** Applies the stored choice at boot, before the first render. */
export function initLanguage() {
  current = loadPrefs().language
  document.documentElement.lang = current
}

export function subscribeLanguage(listener: () => void): () => void {
  listeners.add(listener)
  return () => listeners.delete(listener)
}

/** Snapshot for {@link useT} — changes identity whenever the language does. */
export function languageSnapshot(): Language {
  return current
}
